---
version: "3.8"

services:
  drupal:
    volumes:
      # Reflect changes from running composer updated or modifying configuration
      # and custom modules in the container.
      - &drupal-assets ./drupal/rootfs/var/www/drupal/assets:/var/www/drupal/assets:${CONSISTENCY}
      - &drupal-composer-json ./drupal/rootfs/var/www/drupal/composer.json:/var/www/drupal/composer.json:${CONSISTENCY}
      - &drupal-composer-lock ./drupal/rootfs/var/www/drupal/composer.lock:/var/www/drupal/composer.lock:${CONSISTENCY}
      - &drupal-config ./drupal/rootfs/var/www/drupal/config:/var/www/drupal/config:${CONSISTENCY}
      - &drupal-content ./drupal/rootfs/var/www/drupal/content:/var/www/drupal/content:${CONSISTENCY}
  ide:
    volumes:
      - *drupal-assets
      - *drupal-composer-json
      - *drupal-composer-lock
      - *drupal-config
      - *drupal-content