#!/usr/bin/with-contenv bash
set -e

source /etc/islandora/utilities.sh

# Run as a one-shot service.
s6-svc -O /var/run/s6/services/install

# Wait until nginx and fpm have started.
while ! test -e /var/run/nginx/nginx.pid -a -e /var/run/php-fpm7/php-fpm7.pid; do
  sleep 1;
done

# Wait for services.
wait_for_service default solr
wait_for_service default fcrepo
wait_for_service default broker
wait_for_service default triplestore

wait

# Perform install/import.
cd /var/www/drupal
/usr/local/share/custom/install.sh

touch /installed

cat <<-EOT


#####################
# Install Completed #
#####################
EOT